<img src="http://www.exalumnos.usm.cl/wp-content/uploads/2015/06/Isotipo-Negro.gif" title="Title text" width="20%" height="20%" />


<hr style="height:2px;border:none"/>
<h1 align='center'> INF-395/477 Redes Neuronales Artificiales I-2018 </h1>

<H3 align='center'> Tarea 0 - Introducción a Redes Neuronales </H3>
<hr style="height:2px;border:none"/>

**Temas**  
* NNs por dentro: *back-propagation from scratch*.
* Principales hiperparámetros de *back propagation*
* Introducción a keras
* Verificación numérica de las derivadas implementadas.

** Formalidades **  
* Equipos de trabajo de: 2 personas (*cada uno debe estar en condiciones de responder preguntas sobre cada punto del trabajo realizado*)
* Se debe preparar un (breve) Jupyter/IPython notebook que explique la actividad realizada y las conclusiones del trabajo
* Fecha de entrega: 30 de Marzo.
* Formato de entrega: envı́o de link Github al correo electrónico del ayudante (*<francisco.mena.13@sansano.usm.cl>*) , incluyendo al profesor en copia (*<jnancu@inf.utfsm.cl>*). Por favor especificar el siguiente asunto: [Tarea0-INF395-I-2018]

<hr style="height:2px;border:none"/>


#### Paquetes instalación
Para poder trabajar en el curso se necesitará instalar librerías para Python, por lo que se recomienda instalarlas a través de *anaconda* (para Windows y sistemas Unix) en un entorno virtual, donde podrán elegir su versión de Python. Se instalarán librerías como __[*sklearn*](http://scikit-learn.org/stable/)__, una librería simple y de facil acceso para *data science*, __[*keras*](https://keras.io/)__ en su versión con GPU (para cálculo acelerado a través de la tarjeta gráfica), además de que ésta utiliza como *backend* *TensorFlow* o *Theano*, por lo que habrá que instalar alguno de éstos, además de las librerías básicas de *computer science* como *numpy*, *matplotlib*, *pandas*, además de claramente *jupyter*.

* __[Descargar anacona](https://www.anaconda.com/download/#linux)__ 

* Luego de instalar Anaconda y tenerla en el *path* de su computador crear un entorno virtual: 
```
conda create -n redesneuronales python=version
```

con *version*, la version de Python que desea utilizar. Si está en Windows, se recomienda Python 3 debido a dependencias con una de las librerías a utilziar.
 
* Acceder al ambiente creado 
```
source activate redesneuronales
```

* Instalar los paquetes a utilizar
```
conda install jupyter sklearn numpy pandas matplotlib keras-gpu tensorflow-gpu 
```

* Para salir del entorno
```
source deactivate redesneuronales
```
<hr style="height:1px;border:none"/>


La tarea se divide en cuatro secciones:

[1.](#primero)   Back-propagation (BP) from *Scratch*   
[2.](#segundo)   Comparar back-propagation (BP) de Keras  
[3.](#tercero)   Verificación numérica del gradiente para una componente  
[4.](#cuarto)   Implementar momentum como variante

<a id="primero"></a>
## 1. Back-propagation (BP) from *Scratch*

BP (Back-propagation) es sin duda el paradigma dominante para entrenar redes neuronales *feed-forward*. En
redes grandes, diseñadas para problemas reales, implementar BP eficientemente puede ser una tarea delicada
que puede ser razonable delegar a una librerı́a especializada. Sin embargo, construir BP *from scratch* es muy
útil con fines pedagógicos.

$$ w^{(t+1)} \leftarrow w^{(t)} - \eta \nabla_{w^{(t)}} Loss $$
 
> a) Escriba un programa que permita entrenar una red FF con una arquitectura fija de 2 capa ocultas (con 32 neuronas en la primera capa y 16 en la segunda) y $K$ neuronas de salida, sin usar librerı́as, excepto eventualmente *numpy* para implementar operaciones básicas de algebra lineal. Por simplicidad, asuma funciones de activacion y error (*loss function*) diferenciables o subdiferenciables, además de tener la misma función de activación para las 2 capas ocultas. Adapte la arquitectura para un problema de clasificación de 3 clases, es decir la función de activación para la capa de salida debe ser **softmax** con número de neuronas $K$=3. Escriba funciones para:  
* (i)  implementar el *forward pass*  
* (ii) implementar el *backward pass*  
* (iii) implementar la rutina principal de entrenamiento, adoptando, por simplicidad, la variante cíclica aleatorizada de SGD (un ejemplo a la vez, pero iterando cíclicamente sobre una configuración aleatoria del conjunto de entrenamiento) con una tasa de aprendizaje fija de 0.1 y número de ciclos fijos (*epochs*).

> b) Escriba una función que permita hacer predicciones mediante la red FF definida anteriormente, sin usar librerı́as, excepto eventualmente *numpy*. Escriba una función vectorizada que implemente el forward pass sobre un conjunto de $n_{t}$ ejemplos, además de implementar la función de decisión, que a través de la salida de la red prediga el valor categórico de la clase (1, 2 o 3).

> c) Demuestre que sus programas funcionan en un problema de clasificación. Para esto utilice el dataset **iris**, disponible a través de la librería __[*sklearn*](http://scikit-learn.org)__, el cual corresponde a la clasificación de distintos tipos de plantas de iris (3 clases) mediante 4 características reales continuas específicas de la planta, deberá entrenar (ajustar) los pesos de la red para realizar la tarea encomendada, variando las funciones de error (*loss*) entre *categorical cross entropy* y *mean squared error*, además de variar las funciones de activación para las 2 capas ocultas entre  ReLU (Rectifier Linear Unit) y la función logística (*sigmoid*). Especifique explícitamente las funciones anteriores, así como sus gradientes. Recuerde que debe transformar las etiquetas usando *one hot vectors*.
<div class="alert alert-block alert-info">Es una buena práctica el normalizar los datos antes de trabajar con el modelo</div>
```python
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
X_train,y_train = load_iris(return_X_y=True)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
#transform target to one hot vector
import keras
y_onehot = keras.utils.to_categorical(y_train)
```
Para evaluar los resultados, construya un gráfico correspondiente al error de clasificación versus número
de epochs, utilizando sólo el conjunto de entrenamiento (el objetivo de esta sección es familiarizarse
con el algoritmo BP, no encontrar la mejor red). Grafique también la evolución de la función objetivo utilizada para el entrenamiento. Además de reportar el tiempo de entrenamiento mediante el algoritmo implementado.  
Por último, para alguna configuración elegida, reporte la matriz de confusión mediante el uso de librerías como *sklearn* o *keras*.

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
X_train,y_train = load_iris(return_X_y=True)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
#transform target to one hot vector
import keras
y_onehot = keras.utils.to_categorical(y_train)

En una red neuronal Feed Forward (FF) se cuenta con la capa de entrada, capas ocultas y la capa de salida, dentro de cada capa existe una cantidad variable de neuronas. Toda la información se mueve solo hacia adelante, es decir, desde la capa de entrada, luego hacia las capas ocultas en orden y finalmente la capa de salida. Cada capa posee una función de activación, que generalmente, en las capas ocultas que es una transformación aprendida por cada neurona de la combinación lineal y no linealidad. 

Para este caso, se trabajara una red Feed Forward con:
* Dos capas ocultas: 32 neuronas la primera y 16 neuronas la segunda.
* La capa de salida posee 3 neuronas ,debido a que se desea clasificar entre tres clases.
* La función de activación de las capas ocultas será la función sigmoidal y para la capa de salida una función sofmax.
* La función de pérdida será inicialmente con una función cross entropy.

Para entrenar una red FF se deben realizar principalmente tres pasos por cada ejemplo del entrenamiento, y estos a su vez se van iterando:

1) El primer paso es implementar el *forward pass*, el cual realiza la predicción de la red. Este paso se le entrega un input a la red, el cual se va transformando a medida que pasan por las capas, hasta llegar a la última capa y entregar el output correspondiente. Desde la capa de entrada el input pasa a la primera capa oculta, en donde se realiza una combinación lineal de las neuronas con sus respectivos pesos de la capa de entrada en cada una de las 32 neuronas, y luego se le aplica la función de activación sigmoidal. Lo mismo ocurre con la segunda capa oculta, en que se realiza una combinación lineal de la capa anterior por cada neurona y luego se aplica la función de activación sigmoidal. Finalmente, para la ultima capa se realiza el mismo procedimiento, solo cambia que la función de activación es la sofmax.

2) A continuación se mide el error y la función de pérdida, obtenida del resultado anterior del forward pass

3) Finalmente se debe implementar el *backward pass*, el cual corrige los pesos obtenidos en cada capa según la pérdida observada en el paso anterior. Se parte de la última capa hasta llegar a la primera. Aquí se modifican los pesos disminuyendo la tasa de aprendizaje entregada como parámetro por la derivada parcial del error respecto al peso correspondiente.

Como se mencionó anteriormente, los pasos se deben repetir la cantidad de veces como ejemplos de entrenamiento existan, es decir aplicar el método de SGD, donde se evalúa ejemplo por ejemplo.

A continuación se encuentra la implementación que esta comentada con lo realizado en cada paso.

In [16]:
import numpy as np

epsilon =  1e-15
#----funcion de activacion y gradiente
def sigmoid(x):
    if x > 0:
        x = np.maximum(epsilon, x) #si x es muy pequeño
    #if x < 0:
    #    x = np.maximum(-600,x)  #si x es muy negativo
    return 1 / (1 + np.exp(-x))
    
def gradient_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

def softmax(x):
    retorno = np.zeros(len(x))
    suma = 0.0
    for i in x:
        valor = np.maximum(epsilon,i)
        suma+=np.exp(valor)
    for i in range(len(x)):
        valor = np.maximum(epsilon,x[i])
        retorno[i] = np.exp(valor)/suma #salida normalizada
    return retorno

def gradient_softmax(x):
    return softmax(x) * (1 - softmax(x))

def relu(x):
    return np.maximum(x, 0)

def gradient_relu(x):
    return 1. * (x > 0)

#---funcion de perdida y gradiente
def loss_function(y, ypred, type_error="cross_entropy"):
    ypred = np.maximum(epsilon, ypred)
    if type_error == "cross_entropy":
        return -1.0 * (y * np.log(ypred) + np.subtract(1, y) * np.log(np.subtract(1, ypred)))
    else:
        # quadratic error
        return pow(y - ypred, 2) / 2

def gradient_loss_function(y, ypred, type_error="cross_entropy"):
    ypred = np.maximum(epsilon, ypred)
    if type_error == "cross_entropy":
        return -1.0* (y - ypred) / (ypred * np.subtract(1, ypred))
    else:
        #error cuadratico
        return y-ypred
    
def init_network(n_input, hidden_neurons, n_output, L):
    S = [n_input] + hidden_neurons + [n_output]
    
    #inicializan matrices de salidas de neuronas
    A = []
    A_derivate = [] 
    #inicializa matrices que guardan los errores
    error_outputs = []
    error_weights = []
    #inicializa pesos de la red
    network_weights = []
    
    for l in range(L):
        A.append(np.zeros(S[l])) #salida de capa l
        A_derivate.append(np.zeros(S[l]))       #salida derivada de capa l
        error_outputs.append(np.zeros(S[l]))
        
    for l in range(L-1):
        error_weights.append(np.zeros((S[l],S[l+1])))
        network_weights.append(np.random.rand(S[l],S[l+1]))
        
    return S, network_weights, error_weights, error_outputs, A, A_derivate

  
class neural_network:
    
    def __init__(self, layers, type_loss):
        self.n_layers = len(layers)
        self.n_input = layers[0]
        self.n_output = layers[-1]
        self.n_hidden = layers[1:-1]
        self.L = 2 + len(self.n_hidden)  #numero de capas
        self.type_loss = type_loss
        
        # create architecture
        self.S, self.weights, self.e_weights, self.e_output, self.neuron, self.neuron_gradient = init_network(self.n_input,
                                                                                self.n_hidden, self.n_output, self.L)
        
        
    #i) calcular forward pass, predicción de la red, actualizan las salidas
    def forward_pass(self, example):
        x = example[0]
        y = example[1]
        self.neuron[0] = x.copy()
        for l in range(self.L-1): #por cada transicion entre capas {0,L-2}          
            for s in range(self.S[l+1]): #por cada neurona de la capa siguiente
                aux = np.dot(self.weights[l][:,s], self.neuron[l])
                self.neuron[l+1][s] = sigmoid(aux)
                self.neuron_gradient[l+1][s] = gradient_sigmoid(aux)
        #ultima capa softmax
        self.neuron[self.L-1] = softmax(self.neuron[self.L-1])  #prediccion
        self.neuron_gradient[self.L-1] = gradient_softmax(self.neuron[self.L-1])
    
    
    #ii) calcular backward pass, modifica la red considerando el error observado
    def backward_pass(self, example, learning_rate):
        x = example[0]
        y = example[1]
        
        #calcula el error en la ultima capa
        for s in range(self.S[self.L-1]): 
            #arquitectura con multiples salidas (y es un vector)
            ypred = self.neuron[self.L-1]  #.copy()
            self.e_output[self.L-1][s] = gradient_loss_function(y[s], ypred[s], self.type_loss)
            self.e_weights[self.L-2][:,s] = np.dot(self.e_output[self.L-1][s],
                                                       np.dot(self.neuron_gradient[self.L-1][s],
                                                   self.neuron[self.L-2]))

            #actualizar pesos en vector
            self.weights[self.L-2][:,s] = self.weights[self.L-2][:,s] - learning_rate*self.e_weights[self.L-2][:,s]
        #calcula el error recursivamente
        for l in np.arange(self.L-2,0,-1): #desde la penultima capa hasta la segunda {L-2,1}
            for s in range(self.S[l]): #para cada neurona en la capa l
                self.e_output[l][s] = np.sum(self.e_output[l+1])
                self.e_weights[l-1][:,s] =  np.dot( self.e_output[l][s], np.dot(self.neuron_gradient[l][s], 
                                                                                self.neuron[l-1]) )

                #actualizar pesos en vector
                self.weights[l-1][:,s] = self.weights[l-1][:,s] - learning_rate*self.e_weights[l-1][:,s]
            


    #iii) estrategia principal de entrenamiento
    def train(self, X, Y, epoch, learning_rate):
        data = list(zip(X, Y)) 
        np.random.shuffle(data)  #desordenar los ejemplos
        
        loss_epochs = []
        error_epochs = []

        for i in range(epoch):
            loss = []
            error = []
            #print(i)
            #print(len(list(data)))
            for example in data: #con sgd un ejemplo a la vez
                self.forward_pass(example)
                #measure_error(network, example)
                
                #medir el error y loss
                ypred = self.neuron[self.L - 1].copy()
                #print("example")
                #print(ypred)
                loss.append(loss_function(example[1], ypred, self.type_loss))
                error.append(1 - example[1][np.argmax(ypred)])
                print(example[1])
                print(np.argmax(ypred))
                print(example[1][np.argmax(ypred)])
                
                self.backward_pass(example, learning_rate)
            
            #print(loss)
            loss_epochs.append(np.mean(loss))
            error_epochs.append(np.mean(error))
            #print("loss " + str(loss_epochs[-1]))
            
        return loss_epochs, error_epochs
        

n_inputs = 10
info = [n_inputs, 32, 16, 3]
nn = neural_network(info, "cross_entropy")

b) Escriba una función que permita hacer predicciones mediante la red FF definida anteriormente, sin usar librerı́as, excepto eventualmente numpy. Escriba una función vectorizada que implemente el forward pass sobre un conjunto de  ntnt  ejemplos, además de implementar la función de decisión, que a través de la salida de la red prediga el valor categórico de la clase (1, 2 o 3).

In [4]:
#FF  = red ya entrenada
def predecir(X_test,y_test,FF):
    n_test = len(y_test)
    print("numero de ejemplos: " + n_test)
    
    predicciones = []
    for xi,yi in zip(X_test,y_test): #para n_test ejemplos
        y_hat = forward_pass(xi,yi,FF.L,FF.WM, FF.A,FF.A_der,FF.S)
        predicciones.append(y_hat)
    return predicciones

c) Demuestre que sus programas funcionan en un problema de clasificación. Para esto utilice el dataset iris, disponible a través de la librería sklearn, el cual corresponde a la clasificación de distintos tipos de plantas de iris (3 clases) mediante 4 características reales continuas específicas de la planta, deberá entrenar (ajustar) los pesos de la red para realizar la tarea encomendada, variando las funciones de error (loss) entre categorical cross entropy y mean squared error, además de variar las funciones de activación para las 2 capas ocultas entre ReLU (Rectifier Linear Unit) y la función logística (sigmoid). Especifique explícitamente las funciones anteriores, así como sus gradientes. Recuerde que debe transformar las etiquetas usando one hot vectors.

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import keras

X_train,y_train = load_iris(return_X_y=True)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

#transform target to one hot vector
y_onehot = keras.utils.to_categorical(y_train)

In [18]:
print(X_train)
print(y_train)

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e

In [17]:
import time

layers = [X_train.shape[1], 32, 16, 3]
FF_mse = neural_network(layers, type_loss="cross_entropy")

start_time = time.time()
cross_loss, cross_error = FF_mse.train(X_train, y_onehot, epoch = 100, learning_rate = 0.5)
print("-- training time: %s [s] --" % (time.time() - start_time))

[0. 1. 0.]
2
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0

[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0

[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1

[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0

[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1

[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0

[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1

[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0

[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0

[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1

[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0

[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0

[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0

[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0

[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
0
0

[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
2
1.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0

[0. 1. 0.]
0
0.0
[1. 0. 0.]
2
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1

[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0

[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0

[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 1. 0.]
2
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
2
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1

[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0

[1. 0. 0.]
1
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0

[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0

[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0

[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1

[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1

[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1

[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
2
0.0
[0. 0. 1.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 0. 1.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
1
1.0
[0. 1. 0.]
1
1.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0

[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
1
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
1
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[1. 0. 0.]
0
1.0
[0. 1. 0.]
0
0.0
[0. 1. 0.]
0
0.0
[1. 0. 0.]
0
1.0
[0. 0. 1.]
0
0.0
[0. 0. 1.]
0
0.0
[0. 1. 0.]
0
0

In [20]:
print(cross_loss)

[0.6296492428319058, 0.657206748547468, 0.6492757267924081, 0.6433287045165336, 0.643145439328395, 0.6427305617585638, 0.6430976429872064, 0.6436633244347006, 0.6438563131106319, 0.6436102546991684, 0.6434612271296704, 0.6426989388521247, 0.6420956696195376, 0.647494631457792, 0.638328896507172, 0.6478303437310514, 0.6449548420820029, 0.6422974885792645, 0.6487483689024222, 0.6470890337758013, 0.6472337582075736, 0.646986564163812, 0.6470227150653436, 0.6470741484877056, 0.6471135296071839, 0.6471458258510594, 0.6471773463047567, 0.6472117100338839, 0.6472506119225295, 0.6472950374402683, 0.6473458181223125, 0.6474036758936166, 0.647469211754865, 0.6475431159537959, 0.6476269194218011, 0.6477213462999007, 0.6478133664437014, 0.6480118620621091, 0.6481570918659243, 0.6482666126778989, 0.6483731311136729, 0.6484753892224109, 0.648570738509972, 0.6486519410014497, 0.6486764569581968, 0.6484717304706663, 0.6476729644936753, 0.6454256699432984, 0.6440068086755218, 0.6476437409880523, 0.6411

In [19]:
print(cross_error)

[0.6666666666666666, 0.6733333333333333, 0.6866666666666666, 0.7066666666666667, 0.72, 0.7066666666666667, 0.6933333333333334, 0.7066666666666667, 0.74, 0.7333333333333333, 0.7666666666666667, 0.7733333333333333, 0.7666666666666667, 0.7133333333333334, 0.7333333333333333, 0.7533333333333333, 0.7466666666666667, 0.7333333333333333, 0.6866666666666666, 0.6866666666666666, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.7, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6933333333333334, 0.6866666666666666, 0.6866666666666666, 0.6866666666666666, 0.6866666666666666, 0.6866666666666666, 0.7, 0.7066666666666667, 0.7266666666666667, 0.7266666666666667, 0.72, 0.7, 0.7333333333333333, 0.74, 0.7, 0.7, 0.7, 0.7, 0.7, 0.6933333333333

In [ ]:
FF_mse = neural_network(layers, type_loss="mse")

start_time = time.time()
mse_loss, mse_error = FF_mse.train(X_train, y_onehot, epoch = 100, learning_rate = 0.5)
print("-- training time: %s [s] --" % (time.time() - start_time))

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

plt.plot(cross_error)
plt.plot(cross_loss)
#plt.title('')
#plt.ylabel('Classification error')
#plt.xlabel('Epoch')
plt.legend(['Cross error', 'Cross loss'], loc='upper left')
plt.show()

#plt.plot(loss, label='Acc')
#plt.title('')
#plt.ylabel('Classification error')
#plt.xlabel('Epoch')
#plt.legend(['train'], loc='upper left')
#plt.show()

<a id="segundo"></a>
### 2. Comparar back-propagation (BP) de Keras

Keras es una de las librerı́as más populares para desarrollar nuevos modelos de redes neuronales o implementar eficientemente modelos conocidos con fines prácticos, puesto que ofrece una interfaz para poder trabajar de una manera mucho mas simple además de permitir también el manejo de configuraciones mas específicas.  
Como actividad pedagógica ahora se les pide comparar el algoritmo implementado por ustedes con el de alto nivel de la librería __[keras](https://keras.io/)__ . Se les pedirá comparar sobre el mismo dataset con la misma arquitectura utilizada anteriormente, es decir, dos capas ocultas (con 32 y 16 neuronas respectivamente), 3 neuronas en la capa de salida con función de activación softmax, optimizador Gradiente Descentente (GD) con tasa de aprendizaje fija.

<img src="https://i.imgur.com/hUjFUDU.png" width="40%" height="40%" />


> a) Defina, a través de la interfaz de keras, la arquitectura de la red, con las funciones de activación para comparar con la sección anterior.
```python
from keras.models import Sequential
from keras.layers.core import Dense
model = Sequential()
model.add(Dense(32, input_dim=X_train.shape[1], activation="sigmoid or relu"))
model.add(Dense(16, activation="sigmoid or relu"))
model.add(Dense(3, activation="softmax"))
```

> b) Defina, a través de la interfaz de keras, el optimizador de la red, en conjunto con la función de error, para poder comparar con la sección anterior.
```python
from keras.optimizers import SGD
model.compile(optimizer=SGD(lr=0.1),loss="categorical_crossentropy or mse", metrics=["accuracy"])
```

> c) Entrene (ajuste) los pesos de la red definida mediante keras, reportando los mismos gráficos de la sección anterior para poder comparar. Si hay diferencias en la convergencia del algoritmo ¿A qué podría deverse? si hay una gran diferencia en los tiempos de entrenamiento ¿A qué podría deverse?
```python
model.fit(X_train, y_onehot, epochs=100, batch_size=1, verbose=1)
```

In [ ]:
from keras.models import Sequential
from keras.layers.core import Dense

model = Sequential()
model.add(Dense(32, input_dim=X_train.shape[1], activation="sigmoid"))
model.add(Dense(16, activation="sigmoid"))
model.add(Dense(3, activation="softmax"))

In [ ]:
from keras.optimizers import SGD
model.compile(optimizer=SGD(lr=0.1),loss="categorical_crossentropy", metrics=["accuracy"])

In [ ]:
start_time = time.time()
history = model.fit(X_train, y_onehot, epochs=100, batch_size=1, verbose=1)
print("-- training time: %s [s] --" % (time.time() - start_time))

error = list(map(lambda x: 1 - x, history.history['acc']))
loss = history.history['loss']

In [ ]:
#import matplotlib.pyplot as plt
#plt.style.use('ggplot')

plt.plot(error, label='Acc')
#plt.title('')
plt.ylabel('Classification error')
plt.xlabel('Epoch')
plt.legend(['train'], loc='upper left')
plt.show()

plt.plot(loss, label='Acc')
#plt.title('')
#plt.ylabel('Classification error')
#plt.xlabel('Epoch')
plt.legend(['train'], loc='upper left')
plt.show()


- error clasificacion vs epochs (solo con entrenamiento)
- Grafique también la evolución de la función objetivo utilizada para el entrenamiento
- Además de reportar el tiempo de entrenamiento mediante el algoritmo implementado. 
-------------------------------------
- Loss: valor escalar que se trata de minimizar durante el entrenamiento de un modelo. Mientras menos sea , más cercanas son las predicciones a las etiquetas verdaderas.
- Epoch es una pasada completa sobre todos los datos de entrenamiento. 

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

predictions = model.predict(X_train, verbose=1)
y_pred = np.argmax(predictions, axis=1)

target_names = ["Iris Setosa", "Iris Versicolor", "Iris Virginica"]
print(classification_report(y_train, y_pred, target_names=target_names))
print("Matriz de confusión")
print(confusion_matrix(y_train, y_pred))

c) La matriz de confusión (o error matrix) es una herramienta que permite visualizar el desempeño de un algoritmo en machine learning, especialmente con algoritmos supervisados (en el caso de no supervisados se utiliza la matriz de matching). Cada fila de la matriz representa las instancias en una clase predecida, mientras que las columnas representan las instancias en una clase real. Tiene un especial uso para analizar cuándo un clasificador tiene confusión entre dos clases. Para este experimento se utilizará la matriz proporcionada por la librería *sklearn*.

Antes de mostrar la matriz de confusión se muestra el reporte de clasificación de la red neuronal. Esta información ayudará para complementar los resultados de la matriz de confusión. El reporte de clasificación muestra las siguientes métricas para cada clase o etiqueta:

- *Precision*: Capacidad del clasificador de no etiquetar como positiva una muestra que es negativa, y viceversa.
- *Recall*: Capacidad del clasificador para encontrar todas las muestras positivas/relevantes.
- *F1-Score*: Puede interpretarse como una media armónica ponderada de precision y recall.
- *Support*: Cantidad de ocurrencias de cada clase.

En el ejemplo anterior se puede ver como la red es capaz de clasificar los datos pertenecientes a la clase Iris Setosa, con un 100% de *precision* y *recall*. En el caso de la segunda clase, Iris Versicolor, se logra clasificar correctamente 49 datos de cincuenta, teniendo un error de 1 caso en que se le asigna la etiqueta de la tercera clase. Para la tercera clase,  se clasifica mal un dato con la clase dos y etiqueta correctamente 49 casos. En conclusión, la red se comporta bien como clasificador, etiquetando mal una pequeña cantidad de los datos. Para la clase dos y tres el valor de *precision* y *recall* disminuye y es igual pues cometen el mismo error de clasificación pero aciertan en el mismo número de casos. Esto puede deberse a puntos en el espacio es tienen características muy similares a los datos de la tercera clase.

<a id="tercero"></a>
### 3. Verificación numérica del gradiente para una componente

En esta sección deberá verificar numéricamente el gradiente para los parámetros del modelo (que en este caso son los pesos de la red), que hasta ahora a definido de manera analítica en su programa, por ejemplo la derivada de $x^2$ es $2x$. Ahora deberá verificar estos cálculos usando la definición de gradiente.

$$ \nabla_{w} Loss = \lim_{\epsilon \rightarrow 0} \frac{Loss(w+ \epsilon)-Loss(w)}{\epsilon} $$

Debido a que el *forward propagation* es relativamente fácil de implementar, se puede confiar en que se realizó de manera correcta, por lo que el cómputo del error (*loss*) debería ser correcto. Esto significa que podemos verificar el gradiente o la derivada analítica del error $\frac{\partial Loss}{\partial w}$ comprobando que el resultado obtenido es similar (dentro de una tolerancia numérica, por ejemplo $10^6$) al valor que obtenemos aplicando la fórmula anterior. Naturalmente interpretaremos $\lim_{\epsilon \rightarrow 0}$ como un valor "*suficientemente pequeño*" de $\epsilon$.


> a) Para un peso escogido aleatoriamente entre la primera capa de la red (*input*) y la primera capa oculta, calcule el valor del gradiente de la función de error para ambas funciones utilizadas (ayúdese mediante las funciones de *backward pass* implementadas anteriormente), luego compare y verifique con el valor numérico del gradiente mediante el procedimiento explicado anteriormente.

> b) Vuelva a verificar el valor del gradiente para otros dos pesos escodigos aleatoriamente en la primera operación de la red. Compare y concluya.

<a id="cuarto"></a>
### 4. Implementar *momentum* como variante

En esta sección deberá construir, sin usar librerı́as, excepto eventualmente *numpy* para implementar operaciones básicas de algebra lineal, una variante del programa definido anteriormente ([sección 1](#primero)) que entrene la red utilizando *momentum* clásico.

$$ v^{(t+1)} \leftarrow \mu v^{(t)} - \eta \nabla_{w^{(t)}} Loss \\
w^{(t+1)} \leftarrow w^{(t)} + v^{(t+1)}
$$

> *Sutskever, I., Martens, J., Dahl, G., & Hinton, G. (2013, February). On the importance of initialization and momentum in deep learning. In International conference on machine learning (pp. 1139-1147).*


Demuestre que su programa funciona en el mismo problema de clasificación presentado anteriormente, para esto, además deberá construir un gráfico de la función de error o pérdida (*loss*) *vs* el número de *epochs* y comentar/analizar la convergencia. ¿Es una mejora significativa? 